### ISSUE TITLE
add disable policy flow

### ISSUE THREAD

**Issue by zeroknots** [erc7579/smartsessions#10]
https://github.com/erc7579/smartsessions/blob/main/contracts/SmartSessionBase.sol#L40-L60

**Comment by filmakarov** [comment]
also all kinds of renounce options:

- renounce policy
- renounce signerId
- renounce the enableData+signature that has not been used yet

https://github.com/bcnmy/smart-account-modules/blob/d88c14fc772b460e160602ab081db2fbcdb250cf/contracts/validators/PermissionManager.sol#L902-L989
