### ISSUE TITLE
Issues with SignerId generation

### ISSUE THREAD

**Issue by filmakarov** [erc7579/smartsessions#15]
[This commit ](https://github.com/erc7579/smartsessions/commit/495b4a9956afe24faf801df780dc9b01d5bc1907) suggests the following way of generating SignerId:
```
signerId = SignerId.wrap(keccak256(abi.encode(isigner, isignerInitData)));
```
and this is verified here 
https://github.com/erc7579/smartsessions/blob/a2a299643183e32b16ad68b84c73572eeb875f42/contracts/SmartSession.sol#L123-L125

The potential issues with this approach are the following:

### No session key signature verification required flow

~~When there is no signature required, `NO_SIGNER_REQUIRED` constant is used as an `ISigner` address.~~
Decided to use YesSigner for cases, when there is no need of verifying signature for a given operation (i.e recurring payments etc)
Obviously, when setting up the Permission with YesSigner as `ISigner`, there will be no init data required.
Thus, if we stick to the `SignerId` being derived from `ISigner` address and `isignerInitData` only, using `0x` data would lead to config collisions as the `SignerId` will be the same if there are several Permissions that do not require session key signature verification flow.
**Potential solution:** put the salt into the `isignerInitData`. Should we check on-chain, that the data is not empty?

### Add policies to the existing Permission (ISigner is already set)

Currently, the following approach is used
https://github.com/erc7579/smartsessions/blob/a2a299643183e32b16ad68b84c73572eeb875f42/contracts/SmartSession.sol#L139-L141

However, now, since we require signerId to be derived of the `enableData.isigner, enableData.isignerInitData`, we can not use `address(0)` in the `enableData.isigner` to skip enabling ISigner.
As in this case, the signerId is different and we won't be able to access data associated with the existing SignerId.
Using the same `enableData.isigner, enableData.isignerInitData` would lead to several excess `SSTORE`'s

Another potential issue, related to the same logic is that it won't be able to replace ISigner and it's config for an existing permission. Providing different `enableData.isigner, enableData.isignerInitData` would lead to different `SignerId`, so it wouldn't be possible to set another signer for an existing set of Policies. It will require re-configuring policies again => plenty of excess `SSTORE`'s

### ~~WalletConnect Cosigner tests~~

~~Currently, in tests, empty SignerId is used.
If changed to non-empty SignerId generated according to the introduced approach from ISigner and initData, it leads to failing tests.~~

**Comment by zeroknots** [comment]
whats the usecase of skipping signature checks entirely? 

wouldnt it be easier to handle this edge case by an ISigner that just doesnt check signature?

**Comment by filmakarov** [comment]
For example, when this is the Subscription (Recurring Payment) permission, that can be triggered by no matters which caller.

> wouldnt it be easier to handle this edge case by an ISigner that just doesnt check signature?

Yes, it can be handled by YesSigner. However, with this approach the problem is still there. `SignerId` will be still the same, unless the initData is different.
Also, having YesSigner and calling it will introduce extra gas compared to just skipping the call.

**Comment by filmakarov** [comment]
The above case will be considered an edge case and it is recommended to remove the full permission in this case and configure the new one.
