### ISSUE TITLE
Can push same ActionId into `enabledActionIds` twice

### ISSUE THREAD

**Issue by filmakarov** [erc7579/smartsessions#16]
https://github.com/erc7579/smartsessions/blob/a2a299643183e32b16ad68b84c73572eeb875f42/contracts/lib/ConfigLib.sol#L73-L75

It is currently possible to push same ActionId into `Bytes32ArrayMap4337 enabledActionIds` twice or more. When further this storage is used to retrieve `ActionId`'s which have been enabled for a given SignerId and SmartAccount during renouncing procedure, the same ActionId will be returned and thus used to get lists of the policies several times. Which will break the logic on the second occurrence, as the required policies will already be disabled.

Potential solution: introduce the check, so the same element can not be pushed to `Bytes32ArrayMap4337` twice

**Comment by zeroknots** [comment]
yea I think adding this check makes a lot of sense

**Comment by filmakarov** [comment]
@zeroknots is it still actual?

**Comment by filmakarov** [comment]
Fixed / merged
