### ISSUE TITLE
Min Policies to Enforce = 1 may prevent some ERC-7715 flows

### ISSUE THREAD

**Issue by filmakarov** [erc7579/smartsessions#23]
While testing sample ERC-7715 request stumbled upon case, when Permissions Request may be made in a way that it does not imply any userOp Policies at all.

For example:

```
{   
            address: '0xffb6a827DAA828004EB1cf8429aA30Fc8ADE9281'
            expiry: 1680307200
            permissions: [
                {
                custom: 'donut-purchase',
                data: {
                    target: '0x2a07706473244BC757E10F2a9E86fB532828afe3',
                    functionName: 'increaseValue'
                },
            ],
            signer: {
                type: 'keys',
                data: {
                    ids: ['did:key:zQ3s2kf1NzmeJib8i1PEqQiv4JAfqZJtBJFGBAfbrEbqEZHkgepS8UCE6fstc4scLBQLWXCoRKWgyGjuW2qHWMpEMDpN', 'did:key:zDn4yvQV64KCqdad2DJj4frSGhrMg7BQRV3erDR8ihnt7kFSJ6mZWtnUtPXcgAweUHtQAp8h5QLmufEk9uUDwB3DtM6']
                }
            }
        }
```

So this only requires TimeFrame policy for Action id made of `target` and `increaseValue.selector`

Looks like this can be not a rare case with ERC-7715. Need to think how to handle it.
What security issues may arise from setting `minPoliciesToEnforce: 0`?

**Comment by zeroknots** [comment]
I think this is super dangerous. Ill change this to a constructor arg. I don't think we should allow this to happen.
