### ISSUE TITLE
Add submodules

### ISSUE THREAD

**Issue by filmakarov** [erc7579/smartsessions#45]
✅  ~Uni Policy (filio)~ #51 

Sudo (Yes) Policy (zeroknots)

K1Signer (zeroknots)

⌛  Multikey signer (filio) => postponed ( #49 )

**Comment by zeroknots** [comment]
sudoPolicy done ✅

for the K1 signer, we should be able to use rhinestone's OwnableValidator

https://github.com/rhinestonewtf/core-modules/blob/main/src/OwnableValidator/OwnableValidator.sol
