### ISSUE TITLE
Module type ids for ISessionValidator, IPolicy

### ISSUE THREAD

**Issue by filmakarov** [erc7579/smartsessions#50]
- Need to decide ids for sub-modules.
- Should userOp Policies, action policies, 1271 policies have different type ids?

**Comment by zeroknots** [comment]
hmmm thats a good question. It might make sense that they are different ids. 
Lets pick low numbers tho, cause the registry packs it bitwise with 2^

**Comment by filmakarov** [comment]
See PR #82

**Comment by filmakarov** [comment]
Fixed / merged
