### ISSUE TITLE
Shadowing Declaration of PermissionId in validateUserOp

### ISSUE THREAD

**Issue by zeroknots** [erc7579/smartsessions#89]
We are allocating another PermissionId here.

https://github.com/erc7579/smartsessions/blob/cantina-spearbit-remediated/contracts/SmartSession.sol#L118

overwriting the supplied PermissionId here:
https://github.com/erc7579/smartsessions/blob/cantina-spearbit-remediated/contracts/SmartSession.sol#L91

This allows SDKs to supply two different permissionIDs. I dont think this is security critical, but could lead to bad devex

**Comment by zeroknots** [comment]
If this is desired behavior, I think we should overwrite the variable or allocate another one with a different name

**Comment by filmakarov** [comment]
when remediating the [issue about frontrunning permissionId](https://cantina.xyz/code/cdf37612-211c-4472-9e35-f33b9a4802a4/findings/26) I realized that for enable mode we do not need to pass the permissionId and can save 32 bytes of calldata. Please, check the conversation in the issue.

permissionId provided by unpackMode in enable mode is always bytes32(0) [link](https://github.com/erc7579/smartsessions/blob/4c8d8a14b20a5c0500582ca2d3a5f9e154c95ab6/contracts/lib/EncodeLib.sol#L16)
So yes, you're right, no need to allocate the new var, we just need to overwrite an existing one. That's my typo, the intention was to overwrite.

Thanks for catching it!

**Comment by filmakarov** [comment]
fixed [here](https://github.com/erc7579/smartsessions/pull/83/commits/3622e8a6efa408a2714e68de69a7de878073f01d)
